"""Add session_id to interviews table

Revision ID: da82a63989d2
Revises: 
Create Date: 2025-11-20 16:35:00.891832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da82a63989d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('session_id', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_interviews_session_id'), 'interviews', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interviews_session_id'), table_name='interviews')
    op.drop_column('interviews', 'session_id')
    # ### end Alembic commands ###
